import json,httpx,psycopg
from pathlib import Path
from uuid import uuid4
from playwright.sync_api import sync_playwright
R=Path('/home/yyh/project/lifeweave');H=R/'.runtime/independent-web-review';E=R/'docs/evidence/web-research';d=json.loads((H/'downstream-fixture.json').read_text());m=json.loads((H/'manifest.json').read_text());base='http://127.0.0.1:8013';c=httpx.Client(base_url=base+'/api/lifeweave/personal');checks=[]
def note(name,ok,detail):checks.append({'name':name,'result':'pass' if ok else 'fail','detail':detail});(E/'independent-overlap-checks.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2));print(name,checks[-1]['result'],str(detail)[:260],flush=True)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/home/yyh/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome');page=b.new_page();page.goto(base+'/lifeweave/personal/knowledge?source=local&path='+d['path']);page.get_by_role('button',name='下载阅读版',exact=True).wait_for()
 with page.expect_download() as download:page.get_by_role('button',name='下载阅读版',exact=True).click()
 dest=H/'reading.html';download.value.save_as(dest);export=b.new_page();export.goto(dest.as_uri());export.locator('img').scroll_into_view_if_needed();export.wait_for_function('document.querySelector("img").naturalWidth>0');source=export.get_by_role('link',name='来源文本',exact=True).get_attribute('href');note('实际打开导出HTML图片与引用仍可用',export.locator('img').evaluate('(e)=>e.naturalWidth')==1 and httpx.get(source).status_code==200,{'url':source,'image':export.locator('img').get_attribute('src')})
 doc=c.get('/library/document',params={'path':d['path']}).json();item=c.post('/items',json={'itemType':'research','title':'第二来源同名路径反例'}).json();run=c.post('/runs',json={'itemId':item['id'],'engine':'codex','instruction':'独立受控同名路径fixture'}).json();content='# 第二来源\n\n[第二来源同名路径](research/source.md)\n'
 with psycopg.connect(host=str(R/'.runtime/postgres/socket'),port=55440,user='lifeweave',dbname=m['database'],autocommit=True) as conn:conn.execute("UPDATE workbench.t_lifeweave_run SET state='succeeded',result=%s,finished_at=now() WHERE id=%s",(content,run['id']))
 repo=H/'.runtime/executions/personal'/run['id']/'repo/research';repo.mkdir(parents=True);(repo/'source.md').write_text('# 第二来源\nSOURCE-99，与第一来源不同。')
 response=c.post('/items/'+item['id']+'/knowledge-candidates',json={'runId':run['id'],'path':d['path'],'content':doc['content']+'\n\n'+content,'baseVersion':doc['version'],'reason':'两个来源同名路径应明确冲突','requestId':uuid4().hex});assert response.status_code==201,response.text;draft=response.json();refs=draft['references'];note('两个run同名引用不静默选择任一个',bool(refs['warnings']) and 'research/source.md' not in refs['links'],refs)
 page.goto(base+'/lifeweave/personal/items/'+item['id']+'/outputs');region=page.get_by_role('region',name='知识候选审阅');region.get_by_text(d['path']+' · 等待审阅',exact=True).click();region.get_by_text('阅读建议全文',exact=True).click();region.get_by_text('多个来源使用相同相对引用',exact=False).wait_for();note('事项候选消费者显示歧义',True,region.get_by_text('多个来源使用相同相对引用',exact=False).inner_text())
 region.get_by_role('button',name='接受并更新知识原文').click();region.get_by_text(d['path']+' · 已接受',exact=True).wait_for();region.get_by_role('link',name='阅读已接受知识').click();page.get_by_text('多个来源使用相同相对引用',exact=False).wait_for();accepted=c.get('/library/document',params={'path':d['path']}).json();note('正式知识消费者共享同一冲突结果',accepted['references']==refs,accepted['references']);page.screenshot(path=str(E/'independent-reference-overlap.png'),full_page=True);b.close()
